name: prettier format

on:
  push: 
    branches: [ lint ]
  pull_request:
    branches: [ master ]

jobs:
  format:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install node packages
      run: npm install
    -name: format with prettier
      run: npm run auto-format
    - name: check format with prettier
      run: npm run format
    - name: Commit format changes
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action [bot]"
        git commit -m "making it prettier" -a
        git push
